# RegionAI Configuration File
# This file contains default configuration settings

visualization:
  # Transparency settings
  default_alpha: 0.3
  highlight_alpha: 0.6
  
  # Color scheme
  colors:
    default: blue
    selection: red
    contained: green
    overlap: yellow
    
  # Plot settings
  figure:
    width: 10
    height: 10
    dpi: 100
    
  # Grid and axes
  show_grid: true
  grid_alpha: 0.3
  
  # Interaction
  highlight_linewidth: 3.0
  label_fontsize: 10
  
  # Debug mode
  debug:
    show_coordinates: true
    show_volume: true
    coordinate_fontsize: 8

# Computation settings
computation:
  device: auto  # auto, cpu, or cuda
  precision: float32
  
# Analysis settings
analysis:
  max_hierarchy_depth: 10
  detect_cycles: true
  
# Event system settings  
events:
  max_history: 1000
  enable_logging: false
  
# Selection behavior
selection:
  default_mode: single  # single, multiple, hierarchical
  default_highlight: related  # none, contained, overlapping, ancestors, descendants, related